before_script:
  - npm install

stages:
  - test

node_4:
  image: node:4.3-slim
  stage: test
  script:
    - node ./node_modules/.bin/istanbul cover ./tests/test.js

node_5:
  image: node:5.6-slim
  stage: test
  script:
    - node ./node_modules/.bin/istanbul cover ./tests/test.js
